#!/usr/bin/env bash
# =============================================================================
# Sentinel AI — VPS Deploy Script
# Safe to re-run. Won't touch your other sites.
#
# Usage:
#   1. Copy the entire project to /opt/sentinel-ai on your VPS
#   2. Edit /opt/sentinel-ai/.env (set DOMAIN, AUTH_SECRET, DEEPSEEK_API_KEY)
#   3. Run: chmod +x deploy.sh && sudo ./deploy.sh
# =============================================================================

set -euo pipefail

APP_DIR="/opt/sentinel-ai"
APP_NAME="sentinel-ai"
PORT="3000"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ---------------------------------------------------------------------------
# 1. Check we're in the right directory
# ---------------------------------------------------------------------------
cd "$APP_DIR" || err "Project directory $APP_DIR not found. Copy the project there first."

# ---------------------------------------------------------------------------
# 2. Load .env for domain
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  err "No .env file found. Create one from .env.example first."
fi

set -a; source .env; set +a

DOMAIN="${DOMAIN:-}"
if [ -z "$DOMAIN" ]; then
  err "DOMAIN is not set in .env. Add 'DOMAIN=your-domain.com' to .env"
fi

log "Deploying Sentinel AI to https://$DOMAIN"

# ---------------------------------------------------------------------------
# 3. System packages (Node.js, Nginx, Certbot)
# ---------------------------------------------------------------------------
log "Checking system dependencies..."

if ! command -v node &>/dev/null; then
  warn "Node.js not found. Installing Node 22..."
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt update && sudo apt install -y nodejs
fi

NODE_VERSION=$(node --version)
log "Node.js $NODE_VERSION"

if ! command -v nginx &>/dev/null; then
  warn "Nginx not found. Installing..."
  sudo apt update && sudo apt install -y nginx
fi
log "Nginx $(nginx -v 2>&1)"

if ! command -v certbot &>/dev/null; then
  warn "Certbot not found. Installing..."
  sudo apt update && sudo apt install -y certbot python3-certbot-nginx
fi
log "Certbot OK"

if ! command -v pm2 &>/dev/null; then
  warn "PM2 not found. Installing globally..."
  sudo npm install -g pm2
fi
log "PM2 $(pm2 --version)"

# ---------------------------------------------------------------------------
# 4. Node dependencies
# ---------------------------------------------------------------------------
log "Installing dependencies..."
npm ci --production

# ---------------------------------------------------------------------------
# 5. Database setup
# ---------------------------------------------------------------------------
log "Generating Prisma client..."
npm run db:generate

log "Running database migrations..."
npm run db:migrate

log "Seeding database (idempotent)..."
npm run db:seed

# ---------------------------------------------------------------------------
# 6. Build
# ---------------------------------------------------------------------------
log "Building Next.js app..."
npm run build

# ---------------------------------------------------------------------------
# 7. PM2 — start/restart the app
# ---------------------------------------------------------------------------
if pm2 describe "$APP_NAME" &>/dev/null; then
  log "Restarting existing PM2 process..."
  pm2 restart "$APP_NAME"
else
  log "Starting new PM2 process on port $PORT..."
  pm2 start npm --name "$APP_NAME" -- start
fi

pm2 save
# Auto-start on reboot (idempotent)
pm2 startup systemd -u "$(whoami)" --hp "$HOME" 2>/dev/null || true
log "PM2 process running on port $PORT"

# ---------------------------------------------------------------------------
# 8. Nginx — add site config (does NOT touch your existing sites)
# ---------------------------------------------------------------------------
NGINX_CONF="/etc/nginx/sites-available/$APP_NAME"

if [ ! -f "$NGINX_CONF" ]; then
  log "Creating Nginx config for $DOMAIN..."
  sudo tee "$NGINX_CONF" > /dev/null <<NGINXEOF
# Sentinel AI — generated by deploy.sh on $(date)
server {
    listen 80;
    server_name $DOMAIN;

    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
NGINXEOF

  if [ ! -L "/etc/nginx/sites-enabled/$APP_NAME" ]; then
    sudo ln -s "$NGINX_CONF" "/etc/nginx/sites-enabled/$APP_NAME"
  fi
else
  # Config exists — update the domain in case it changed
  log "Updating Nginx config for $DOMAIN..."
  sudo sed -i "s/server_name .*/server_name $DOMAIN;/" "$NGINX_CONF"
fi

sudo nginx -t || err "Nginx config test failed. Check /etc/nginx/sites-available/$APP_NAME"
sudo systemctl reload nginx
log "Nginx configured and reloaded"

# ---------------------------------------------------------------------------
# 9. HTTPS via Certbot
# ---------------------------------------------------------------------------
if sudo certbot certificates 2>/dev/null | grep -q "$DOMAIN"; then
  log "SSL certificate already exists for $DOMAIN. Running renew..."
  sudo certbot renew --nginx --non-interactive
else
  log "Obtaining SSL certificate for $DOMAIN..."
  sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN" --redirect
fi

log "HTTPS enabled for https://$DOMAIN"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================="
echo -e "  ${GREEN}Deploy complete!${NC}"
echo "  https://$DOMAIN"
echo ""
echo "  Manage:"
echo "    pm2 status                  # Check process"
echo "    pm2 logs $APP_NAME          # View logs"
echo "    pm2 restart $APP_NAME       # Restart"
echo ""
echo "  To redeploy after code changes:"
echo "    cd $APP_DIR && git pull && ./deploy.sh"
echo "============================================="
